export const SITE_CONTENT = {
  heroTexts: ['Developer', 'Student', 'Learner', 'Creator', 'Tinkerer', 'Builder'],
  aboutContent: `Hello, I'm Masoom\n"I'm from Gokak, Karnataka, currently in my pre-final year of B.E. in Computer Science (CGPA: 8.4). I am an aspiring web developer and UI/UX designer with a deep passion for modern web development, particularly in creating clean, intuitive frontend designs."\n\nMy Journey\n"While I am still early in my career and constantly learning, I've already started exploring the development ecosystem by building a few projects through 'vibe coding'. For me, coding is as much about the process of discovery as it is about the final product. I love experimenting with new ideas, understanding how interactive web applications function behind the scenes, and figuring out how to bring static mockups to life."\n\nLooking Forward\n"I may not be a professional developer or designer just yet, but my goal is to get there. My current focus is on strengthening my foundation in core web technologies, expanding my toolset, and growing my skills every single day. I'm excited to take on new challenges and eventually build experiences that users will love."`,
  featuredTitle: 'Featured',
  featuredSubtitle: 'A selection of my recent full-stack applications and functional frontends.',
  timelineTitle: 'My Journey',
  timelineSubtitle: 'A timeline of my academic background and educational milestones.',
  contactHeading: "Let's",
  contactSubtitle: "Have a project in mind, or just want to say hi? I'm always open to discussing new opportunities and creative ideas.",
  contactEmail: 'mullamasoom50@gmail.com',
  footerLinks: {
    linkedin: { url: 'https://www.linkedin.com/in/masoommulla/', visible: true },
    github: { url: 'https://github.com/masoommulla', visible: true },
    instagram: { url: '', visible: false },
  },
};

export const PROJECTS = [
  {
    _id: '1',
    title: 'ZenMind Mini',
    description: 'A comprehensive mental wellness application built with the MERN stack. Features guided meditation sessions, mood tracking, journaling, and personalized wellness recommendations powered by AI insights.',
    tech: ['React', 'Node.js', 'MongoDB', 'Express', 'Tailwind CSS'],
    link: 'https://zenmind.onrender.com',
    github: '',
    imageUrl: '/projects/mini.png',
    visible: true,
    order: 0,
  },
  {
    _id: '2',
    title: 'Toastmasters Portal',
    description: 'A full-featured club management portal for KLE Toastmasters. Includes member management, speech tracking, role assignments, meeting agendas, and achievement badges — streamlining the entire club operation.',
    tech: ['React', 'TypeScript', 'Express', 'MongoDB', 'JWT Auth'],
    link: '',
    github: '',
    imageUrl: '/projects/tm.png',
    visible: true,
    order: 1,
  },
  {
    _id: '3',
    title: 'ZenMind Major',
    description: 'The full-scale version of ZenMind with advanced features including real-time community forums, therapist booking system, progress analytics dashboard, and a subscription-based premium tier.',
    tech: ['MERN Stack', 'Socket.io', 'Stripe', 'Redis', 'Framer Motion'],
    link: 'https://zenmind-india.onrender.com/',
    github: '',
    imageUrl: '/projects/major.png',
    visible: true,
    order: 2,
  },
];

export const EDUCATION = [
  {
    _id: '1',
    degree: 'SSLC',
    institution: 'Volart Academy High School',
    year: '2019 - 2020',
    percentage: '80.16%',
    status: 'Completed',
    visible: true,
    order: 0,
  },
  {
    _id: '2',
    degree: 'Pre-University (PUC)',
    institution: 'KLE Society C.S. Angadi College',
    year: '2020 - 2022',
    percentage: '91.33%',
    status: 'Completed',
    visible: true,
    order: 1,
  },
  {
    _id: '3',
    degree: 'B.E. Computer Science',
    institution: 'KLECET Chikodi',
    year: '2023 - 2027',
    percentage: 'CGPA 8.4',
    status: 'In Progress',
    visible: true,
    order: 2,
  },
];
